#!/bin/bash
#PBS -m abe
#PBS -V
#PBS -l nodes=grad06:ppn=16:cluster-Grad,walltime=00:15:00
#PBS -M joao.vieira94@edu.pucrs.br
#PBS -r n
#PBS -j oe
#PBS -d /home/pp12723/t1_relatorio/Maximum-Sum-Subsequence
#############
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo `cat $PBS_NODEFILE | uniq`
echo
echo JOB_ID:
echo `echo $PBS_JOBID`
echo ################

./paralelo 1>> ./dados_par_1.txt 2>> ./dados_par_1.txt
./paralelo 1>> ./dados_par_2.txt 2>> ./dados_par_2.txt
./paralelo 1>> ./dados_par_3.txt 2>> ./dados_par_3.txt

############# If running a sequential or openMP program

sleep 1000

################

echo Final Time is `date`

