#!/bin/bash
#PBS -m abe
#PBS -V
#PBS -l nodes=grad05:ppn=2:cluster-Grad,walltime=03:25:00
#PBS -M joao.vieira94@edu.pucrs.br
#PBS -r n
#PBS -j oe
#PBS -d /home/pp12723/t1_relatorio/Maximum-Sum-Subsequence
#############
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo `cat $PBS_NODEFILE | uniq`
echo
echo JOB_ID:
echo `echo $PBS_JOBID`
echo ################

./paralelo 1> dados_par_11_2t.txt 2> ./tempos_par_11_2t.txt
./paralelo 1> dados_par_22_2t.txt 2> ./tempos_par_22_2t.txt
./paralelo 1> dados_par_33_2t.txt 2> ./tempos_par_33_2t.txt

############# If running a sequential or openMP program


################

echo Final Time is `date`

